"""
Various constant values used in the project
"""

DEFAULT_ALLOW_OVERWRITING_FILES = True

DEFAULT_ASCII_ONLY_REFERENCES = False

DEFAULT_HTML_OUTPUT_PRETTIFIED = False

DEFAULT_HTTPS_MODE = 3

DEFAULT_INCLUDE_FONTS = False
DEFAULT_INCLUDE_HYPERLINKS = True
DEFAULT_INCLUDE_IMAGES = False
DEFAULT_INCLUDE_JAVASCRIPT = True
DEFAULT_INCLUDE_STYLESHEETS = True

DEFAULT_LOAD_THIRD_PARTY_RESOURCE = False

DEFAULT_LOWERED_PATHS = False

DEFAULT_QUEUE_ACCESS_TIMEOUT = 0.1

DEFAULT_REWRITE_REFERENCES = True

DEFAULT_RUNNER_CRASH_ON_ERROR = False

DEFAULT_USER_AGENT_STRING = "Mozilla/5.0 (compatible; WebsiteCrawler)"

DEFAULT_UNIQUE_FILENAMES = False
